part of 'main.dart';

// Modern, everyday Tamil for interface text that previously showed only in
// English. Looked up by [ui] before the older label table.
const _tamilModern = <String, String>{
  'Accident': 'விபத்து',
  'Add Entry': 'பதிவு சேர்',
  'Add Purchased Stock': 'வாங்கிய இருப்பைச் சேர்',
  'Add a cow before recording milk.':
      'பால் பதிவு செய்வதற்கு முன் ஒரு மாட்டைச் சேர்க்கவும்.',
  'Add animals, milk, feed, doctor visits and sales with no network at all.':
      'இணையம் இல்லாமலே கால்நடை, பால், தீவனம், மருத்துவம், விற்பனையைச் சேர்க்கலாம்.',
  'Add cows and calves, open a profile, and review milk, health and timeline records.':
      'மாடுகள், கன்றுகளைச் சேர்த்து profile-ல் பால், மருத்துவம், காலவரிசையைப் பார்க்கலாம்.',
  'Add customer': 'வாடிக்கையாளரைச் சேர்',
  'Add note': 'குறிப்பு சேர்',
  'Add to Stock': 'இருப்பில் சேர்',
  'Add your first cow to start tracking milk, health and ranking.':
      'பால், மருத்துவம், தரவரிசையைக் கண்காணிக்க முதல் மாட்டைச் சேர்க்கவும்.',
  'Admin Name': 'நிர்வாகி பெயர்',
  'Admin permission required': 'நிர்வாகியின் அனுமதி தேவை',
  'Age calculated from date of birth':
      'பிறந்த தேதியிலிருந்து வயது கணக்கிடப்பட்டது',
  'Alambadi': 'ஆலம்பாடி',
  'All Animals': 'அனைத்தும்',
  'Already sold': 'ஏற்கெனவே விற்றது',
  'Amount paid now (0 for later)': 'இப்போது கொடுத்த தொகை (பிறகு என்றால் 0)',
  'Amount received now (0 for later)': 'இப்போது வாங்கிய தொகை (பிறகு என்றால் 0)',
  'Animal': 'கால்நடை',
  'Animal added': 'சேர்க்கப்பட்டது',
  'Animal list downloaded': 'கால்நடைப் பட்டியல் download ஆனது',
  'Animals, ranch milk, feed, doctor visits and ranch sales save on this device without a network. Pending changes sync when connectivity returns. Keep a backup: clearing browser storage removes local records.':
      'மாடுகள், பால், தீவனம், மருத்துவம், விற்பனை எல்லாம் இணையம் இல்லாமலே இந்த போனில் சேமிக்கப்படும். இணையம் வந்ததும் தானாக sync ஆகும். Backup வைத்துக்கொள்ளுங்கள்: browser data அழித்தால் பதிவுகள் போய்விடும்.',
  'Anyone using the same Ranch ID sees the same records after a sync.':
      'அதே Ranch ID பயன்படுத்துபவர்கள் sync ஆன பின் அதே பதிவுகளைப் பார்ப்பார்கள்.',
  'Approval is incomplete. Ask the admin to approve again':
      'ஒப்புதல் முழுமையாகவில்லை. நிர்வாகியிடம் மீண்டும் ஏற்கச் சொல்லுங்கள்',
  'Apr': 'ஏப்',
  'April': 'ஏப்ரல்',
  'Aug': 'ஆக',
  'August': 'ஆகஸ்ட்',
  'Auto Sync OFF': 'தானியங்கி Sync நிறுத்தம்',
  'Automatic catch-up': 'தானியங்கி update',
  'Automatic sync runs after changes, when the app opens and every four hours while it is running. Approved members using the same Ranch ID receive the shared records. Cloud Sync shows status and offers manual sync.':
      'மாற்றம் செய்தவுடன், ஆப் திறக்கும்போது, 4 மணி நேரத்துக்கு ஒருமுறை தானாக sync ஆகும். அதே Ranch ID உள்ள உறுப்பினர்களுக்குப் பதிவுகள் போய்ச் சேரும்.',
  'Available': 'இருப்பு',
  'Backup downloaded': 'Backup download ஆனது',
  'Backup restored successfully': 'Backup வெற்றிகரமாக மீட்கப்பட்டது',
  'Balance after sale': 'விற்ற பின் இருப்பு',
  'Bargur': 'பர்கூர்',
  'Birth registered': 'பிறப்பு பதிவானது',
  'Birth was not saved. Please try again':
      'பிறப்பு சேமிக்கப்படவில்லை. மீண்டும் முயற்சிக்கவும்',
  'Birth, pregnancy, treatments, calves, milk and money records will appear here.':
      'பிறப்பு, சினை, மருத்துவம், கன்றுகள், பால், பணப் பதிவுகள் இங்கே தெரியும்.',
  'Breed Injection Name': 'சினை ஊசி வகை',
  'Breeding': 'இனப்பெருக்கம்',
  'Calculated Amount': 'கணக்கிட்ட தொகை',
  'Calf Name (auto if blank)': 'கன்றின் பெயர் (காலியாக விட்டால் தானாக)',
  'Calf Purchase': 'கன்று வாங்கியது',
  'Calf Sale': 'கன்று விற்பனை',
  'Calf born': 'கன்று பிறந்தது',
  'Calves appear here once you add one or record a birth.':
      'கன்றைச் சேர்த்தாலோ பிறப்பைப் பதிவு செய்தாலோ இங்கே தெரியும்.',
  'Can view, add and edit all ranch data; cannot manage members':
      'எல்லாப் பதிவுகளையும் பார்க்கலாம், சேர்க்கலாம், திருத்தலாம்; உறுப்பினர்களை நிர்வகிக்க முடியாது',
  'Cannot sell more than the milk available today':
      'இன்று இருக்கும் பாலை விட அதிகம் விற்க முடியாது',
  'Cart': 'வண்டி',
  'Cart transport': 'வண்டி சவாரி',
  'Checking availability...': 'கிடைக்கிறதா என்று பார்க்கிறது…',
  'Checking ranch access': 'தொழுவ அனுமதியைச் சரிபார்க்கிறது',
  'Choose Ranch, Vendor or Market when you first enter VIMO. Settings → Preferences changes the purpose and tab order on this device for your account. The first tab is your starting page. All five areas remain accessible.':
      'VIMO-வில் முதலில் தொழுவம், வியாபாரம் அல்லது சந்தையைத் தேர்வு செய்யுங்கள். செட்டிங்ஸ் → விருப்பங்களில் பகுதிகளை இயக்கலாம், tab வரிசையை மாற்றலாம். முதல் tab தொடக்கப் பக்கம்.',
  'Choose an available Ranch ID': 'கிடைக்கும் Ranch ID-ஐத் தேர்வு செய்யவும்',
  'Choose another person': 'வேறு ஒருவரைத் தேர்வு செய்யவும்',
  'Choose your purpose to apply a default layout. In Settings → Preferences, hold a tab and drag it to change its position. The first tab opens on launch.':
      'பயன்பாட்டைத் தேர்வு செய்தால் இயல்பான அமைப்பு வரும். செட்டிங்ஸ் → விருப்பங்களில் ஒரு tab-ஐ அழுத்திப் பிடித்து இழுத்து இடத்தை மாற்றலாம். முதல் tab ஆப் திறக்கும்போது வரும்.',
  'Close': 'மூடு',
  'Cloud Records': 'Cloud பதிவுகள்',
  'Cloud actions need an account. Your local data stays safe either way.':
      'Cloud வசதிக்குக் கணக்கு தேவை. உங்கள் போனில் உள்ள தரவு பாதுகாப்பாக இருக்கும்.',
  'Collected': 'கறந்தது',
  'Complete Excel workbook downloaded': 'முழு Excel கோப்பு download ஆனது',
  'Confirm Password': 'பாஸ்வேர்டை மீண்டும் எழுதவும்',
  'Confirmed': 'உறுதி',
  'Contact (optional)': 'தொடர்பு எண் (விருப்பம்)',
  'Cost / Expense': 'செலவு',
  'Could not create the account': 'கணக்கை உருவாக்க முடியவில்லை',
  'Could not load this photo': 'இந்தப் புகைப்படத்தை ஏற்ற முடியவில்லை',
  'Could not open Photos. Please try again':
      'Photos திறக்கவில்லை. மீண்டும் முயற்சிக்கவும்',
  'Could not open the photo': 'புகைப்படத்தைத் திறக்க முடியவில்லை',
  'Could not save animal. Please try again':
      'சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்',
  'Could not save. Please try again.':
      'சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Counts updated': 'எண்ணிக்கை புதுப்பிக்கப்பட்டது',
  'Cow Purchase': 'மாடு வாங்கியது',
  'Cow Sale': 'மாடு விற்பனை',
  'Create New': 'புதிதாக உருவாக்கு',
  'Create Password': 'பாஸ்வேர்டு உருவாக்கு',
  'Create Ranch': 'தொழுவத்தை உருவாக்கு',
  'Create Ranch ID': 'Ranch ID உருவாக்கு',
  'Create a task with a member, due date and target time. The assignee or an admin can mark it complete.':
      'உறுப்பினர், தேதி, நேரத்துடன் வேலையை உருவாக்கலாம். வேலை ஒதுக்கப்பட்டவர் அல்லது நிர்வாகி முடிந்ததாகக் குறிக்கலாம்.',
  'Customer name': 'வாடிக்கையாளர் பெயர்',
  'Daily, monthly and overall reports combine milk, expenses and sales. Export them from Settings.':
      'தினசரி, மாதாந்திர, மொத்த அறிக்கைகளில் பால், செலவு, விற்பனை இருக்கும். செட்டிங்ஸில் export செய்யலாம்.',
  'Death': 'இறப்பு',
  'Dec': 'டிச',
  'December': 'டிசம்பர்',
  'Delivery Problem': 'பிரசவச் சிக்கல்',
  'Disease': 'நோய்',
  'Doctor': 'மருத்துவர்',
  'Don\'t forget': 'மறந்துவிடாதீர்கள்',
  'Download complete': 'Download முடிந்தது',
  'Downloading ranch data...': 'தொழுவ விவரங்கள் download ஆகிறது…',
  'Dry period started': 'வறட்சிக் காலம் தொடங்கியது',
  'Edit entry': 'பதிவைத் திருத்து',
  'Edit time expired': 'திருத்த நேரம் முடிந்தது',
  'Email or password is incorrect': 'இமெயில் அல்லது பாஸ்வேர்டு தவறு',
  'Empty recording': 'பதிவு காலியாக உள்ளது',
  'Enter Ranch ID': 'Ranch ID-ஐ எழுதவும்',
  'Enter a customer name': 'வாடிக்கையாளர் பெயரை எழுதவும்',
  'Enter a name': 'பெயரை எழுதவும்',
  'Enter a valid value': 'சரியான மதிப்பை எழுதவும்',
  'Enter the ranch name and admin name':
      'தொழுவப் பெயரையும் நிர்வாகி பெயரையும் எழுதவும்',
  'Enter your email first, then tap Forgot password':
      'முதலில் இமெயிலை எழுதி, பிறகு "பாஸ்வேர்டு மறந்துவிட்டதா?" தொடவும்',
  'Enter your name and the Ranch ID':
      'உங்கள் பெயரையும் Ranch ID-யையும் எழுதவும்',
  'Entries you add will appear here.':
      'நீங்கள் சேர்க்கும் பதிவுகள் இங்கே தெரியும்.',
  'Entry': 'பதிவு',
  'Entry details': 'பதிவு விவரம்',
  'Entry options': 'பதிவு விருப்பங்கள்',
  'Evening': 'மாலை',
  'Every 4 hours': '4 மணி நேரத்துக்கு ஒருமுறை',
  'Every day': 'தினமும்',
  'Everyone sharing your Ranch ID sees the same animals and records.':
      'உங்கள் Ranch ID உள்ள அனைவரும் அதே கால்நடைகளையும் பதிவுகளையும் பார்ப்பார்கள்.',
  'Everything works offline': 'இணையம் இல்லாமலும் எல்லாம் இயங்கும்',
  'Expenses downloaded': 'செலவுகள் download ஆனது',
  'Export the complete Excel workbook or individual CSV reports. Full Backup saves a restorable JSON file. Restore Backup replaces this device’s data with the selected backup.':
      'முழு Excel கோப்பு அல்லது தனித்தனி CSV அறிக்கைகளை எடுக்கலாம். Full Backup ஒரு JSON கோப்பாகச் சேமிக்கும். Restore செய்தால் இந்த போனில் உள்ள தரவு மாற்றப்படும்.',
  'Feb': 'பிப்',
  'February': 'பிப்ரவரி',
  'Feed added': 'தீவனம் சேர்க்கப்பட்டது',
  'Female': 'பெண்',
  'Five-minute edit expired': '5 நிமிட நேரம் முடிந்தது',
  'Follows you': 'உங்களைப் பின்தொடர்கிறார்',
  'Food': 'தீவனம்',
  'Fri': 'வெ',
  'Friday': 'வெள்ளி',
  'Full access - manage everything':
      'முழு அனுமதி - எல்லாவற்றையும் நிர்வகிக்கலாம்',
  'Full access, including members and ranch settings':
      'உறுப்பினர்கள், தொழுவ செட்டிங்ஸ் உட்பட முழு அனுமதி',
  'Gir': 'கிர்',
  'Gir Semen': 'கிர் விந்து',
  'Gold Champion': 'தங்க சாம்பியன்',
  'Green Star': 'பச்சை நட்சத்திரம்',
  'HF Cross': 'HF கலப்பு',
  'HF Semen': 'HF விந்து',
  'Health entry': 'மருத்துவப் பதிவு',
  'Income / Sale': 'வருமானம் / விற்பனை',
  'Injection / Medicine': 'ஊசி / மருந்து',
  'Insufficient milk': 'பால் போதவில்லை',
  'Insufficient stock': 'இருப்பு போதவில்லை',
  'Invalid backup file': 'தவறான backup கோப்பு',
  'Invalid image': 'தவறான படம்',
  'Invalid join request': 'தவறான சேரும் கோரிக்கை',
  'Its records stay in your reports.': 'இதன் பதிவுகள் அறிக்கைகளில் இருக்கும்.',
  'Jallikattu': 'ஜல்லிக்கட்டு',
  'Jan': 'ஜன',
  'January': 'ஜனவரி',
  'Jersey Cross': 'ஜெர்சி கலப்பு',
  'Jersey Semen': 'ஜெர்சி விந்து',
  'Join Existing': 'இருப்பதில் சேர்',
  'Join request could not be delivered. Please try again':
      'சேரும் கோரிக்கை போகவில்லை. மீண்டும் முயற்சிக்கவும்',
  'Join request rejected': 'சேரும் கோரிக்கை மறுக்கப்பட்டது',
  'Joined the ranch': 'தொழுவத்துக்கு வந்தது',
  'Jul': 'ஜூலை',
  'July': 'ஜூலை',
  'Jun': 'ஜூன்',
  'June': 'ஜூன்',
  'Kangeyam': 'காங்கேயம்',
  'Lactation period started': 'கறவைக் காலம் தொடங்கியது',
  'Liter': 'லிட்டர்',
  'Load': 'லோடு',
  'Loss': 'இழப்பு',
  'Loss recorded': 'இழப்பு பதிவானது',
  'Maintained for 1 month': '1 மாதம் தொடர்ந்தது',
  'Malai Maadu': 'மலை மாடு',
  'Male': 'ஆண்',
  'Manage animals and records': 'கால்நடைகளையும் பதிவுகளையும் நிர்வகிக்கலாம்',
  'Manager': 'மேலாளர்',
  'Mar': 'மார்',
  'March': 'மார்ச்',
  'May': 'மே',
  'Member removed': 'உறுப்பினர் நீக்கப்பட்டார்',
  'Members join using your permanent Ranch ID. An admin approves requests and controls member roles. Role restrictions still apply in every language.':
      'உறுப்பினர்கள் உங்கள் Ranch ID மூலம் சேருவார்கள். நிர்வாகி கோரிக்கைகளை ஏற்று, பொறுப்புகளை ஒதுக்குவார்.',
  'Milk Own Use': 'சொந்தப் பயன்பாட்டுப் பால்',
  'Milk entry': 'பால் பதிவு',
  'Milk entry details': 'பால் பதிவு விவரம்',
  'Milk records downloaded': 'பால் பதிவுகள் download ஆனது',
  'Milking': 'கறவையில்',
  'Milking started': 'கறவை தொடங்கியது',
  'Milking stopped': 'கறவை நிறுத்தப்பட்டது',
  'Mon': 'தி',
  'Mon, Thu': 'தி, வி',
  'Monday': 'திங்கள்',
  'More': 'மேலும்',
  'Morning': 'காலை',
  'Morning milk entry is ready': 'காலைப் பால் பதிவு தயார்',
  'Mother not found': 'தாய் மாடு கிடைக்கவில்லை',
  'Mud horn practice': 'மண் குத்துதல்',
  'My Ranch': 'என் தொழுவம்',
  'My ranch': 'என் தொழுவம்',
  'Name': 'பெயர்',
  'Native Breed Semen': 'நாட்டு இன விந்து',
  'Native Cow': 'நாட்டு மாடு',
  'Never': 'இல்லை',
  'New born': 'புதிதாகப் பிறந்தது',
  'New member': 'புதிய உறுப்பினர்',
  'New requests will appear here for admin approval.':
      'புதிய கோரிக்கைகள் நிர்வாகியின் ஒப்புதலுக்காக இங்கே தெரியும்.',
  'New task assigned': 'புதிய வேலை ஒதுக்கப்பட்டது',
  'Newborn calf saved and milking restarted':
      'புதுக் கன்று சேமிக்கப்பட்டது; கறவை மீண்டும் தொடங்கியது',
  'No active pregnancy is recorded for this animal':
      'இந்த மாட்டுக்குச் சினைப் பதிவு இல்லை',
  'No additional details': 'கூடுதல் விவரம் இல்லை',
  'No animals available to sell': 'விற்க கால்நடைகள் இல்லை',
  'No audio was recorded': 'ஒலி பதிவாகவில்லை',
  'No calves yet': 'கன்றுகள் இன்னும் இல்லை',
  'No doctor records yet.': 'மருத்துவப் பதிவுகள் இன்னும் இல்லை.',
  'No milk records yet.': 'பால் பதிவுகள் இன்னும் இல்லை.',
  'No network. Check your connection': 'இணையம் இல்லை. சரிபார்க்கவும்',
  'No network. Check your connection and try again':
      'இணையம் இல்லை. சரிபார்த்து மீண்டும் முயற்சிக்கவும்',
  'No photo selected. Please allow Photos access and try again':
      'புகைப்படம் தேர்வாகவில்லை. Photos அனுமதி கொடுத்து மீண்டும் முயற்சிக்கவும்',
  'No record': 'பதிவு இல்லை',
  'No visit': 'வருகை இல்லை',
  'Not enough milk': 'பால் போதவில்லை',
  'Not recorded': 'பதிவு இல்லை',
  'Not set': 'அமைக்கவில்லை',
  'Nothing in the cloud yet.': 'Cloud-ல் இன்னும் எதுவும் இல்லை.',
  'Nothing is lost': 'எதுவும் இழக்கப்படாது',
  'Nov': 'நவ',
  'November': 'நவம்பர்',
  'Oct': 'அக்',
  'October': 'அக்டோபர்',
  'Offline - waiting for network': 'இணையம் இல்லை - காத்திருக்கிறது',
  'Offline ranch records': 'இணையம் இல்லாமல் தொழுவப் பதிவுகள்',
  'Old Age': 'வயது முதிர்வு',
  'One photo could not upload. Other entries can still sync.':
      'ஒரு புகைப்படம் upload ஆகவில்லை. மற்ற பதிவுகள் sync ஆகும்.',
  'Only admins and editors can add cows or calves':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே மாடு/கன்று சேர்க்கலாம்',
  'Only admins and editors can edit animals':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே திருத்தலாம்',
  'Only admins and editors can register a calf birth':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே கன்று பிறப்பைப் பதிவு செய்யலாம்',
  'Only admins and editors can register a newborn calf':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே புதுக் கன்றைப் பதிவு செய்யலாம்',
  'Only admins and editors can save animal details':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே விவரங்களைச் சேமிக்கலாம்',
  'Only admins and editors can sell animals':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே விற்கலாம்',
  'Only admins and editors can sell cows or calves':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே மாடு/கன்று விற்கலாம்',
  'Only admins and editors can update animal status':
      'நிர்வாகியும் எடிட்டரும் மட்டுமே நிலையை மாற்றலாம்',
  'Only the ranch admin can change ranch settings':
      'தொழுவ நிர்வாகி மட்டுமே அமைப்புகளை மாற்றலாம்',
  'Only the ranch admin can change these settings':
      'தொழுவ நிர்வாகி மட்டுமே இவற்றை மாற்றலாம்',
  'Open VIMO to view the update': 'பார்க்க VIMO-வைத் திறக்கவும்',
  'Open a cow profile to see dated birth, pregnancy, treatment, calving, milk and linked financial records. Shared ranch expenses are not assigned to an individual cow.':
      'மாட்டின் profile-ல் பிறப்பு, சினை, மருத்துவம், கன்று ஈனுதல், பால், பணப் பதிவுகளைத் தேதியுடன் பார்க்கலாம்.',
  'Open full photo': 'முழுப் புகைப்படத்தைத் திற',
  'Other': 'மற்றவை',
  'Others': 'இதர செலவு',
  'Participated': 'பங்கேற்றது',
  'Password needs at least 6 characters':
      'பாஸ்வேர்டில் குறைந்தது 6 எழுத்துகள் வேண்டும்',
  'Passwords do not match': 'பாஸ்வேர்டுகள் பொருந்தவில்லை',
  'Pause': 'நிறுத்து',
  'Permission': 'அனுமதி',
  'Permission after approval': 'ஏற்ற பின் அனுமதி',
  'Permission denied': 'அனுமதி இல்லை',
  'Photo': 'புகைப்படம்',
  'Photo could not be uploaded': 'புகைப்படம் upload ஆகவில்லை',
  'Place (optional)': 'ஊர் (விருப்பம்)',
  'Play': 'இயக்கு',
  'Please choose a stronger password': 'இன்னும் வலுவான பாஸ்வேர்டு வைக்கவும்',
  'Please choose an animal': 'கால்நடையைத் தேர்வு செய்யவும்',
  'Please describe the problem': 'உடல்நலப் பிரச்சனையை எழுதவும்',
  'Please enter a valid email': 'சரியான இமெயிலை எழுதவும்',
  'Please enter a valid quantity and price':
      'சரியான அளவையும் விலையையும் எழுதவும்',
  'Please enter an amount': 'தொகையை எழுதவும்',
  'Please enter the customer name': 'வாடிக்கையாளர் பெயரை எழுதவும்',
  'Please enter the expense amount': 'செலவுத் தொகையை எழுதவும்',
  'Please enter the expense name': 'செலவின் பெயரை எழுதவும்',
  'Please enter the milk quantity': 'பால் அளவை எழுதவும்',
  'Please enter the purchase amount': 'வாங்கிய தொகையை எழுதவும்',
  'Please enter the purchased quantity': 'வாங்கிய அளவை எழுதவும்',
  'Please enter the quantity': 'அளவை எழுதவும்',
  'Please enter the sale amount': 'விற்பனைத் தொகையை எழுதவும்',
  'Please select a cow': 'மாட்டைத் தேர்வு செய்யவும்',
  'Please select a customer': 'வாடிக்கையாளரைத் தேர்வு செய்யவும்',
  'Please select a customer or supplier':
      'வாடிக்கையாளர் அல்லது விற்பவரைத் தேர்வு செய்யவும்',
  'Please sign in again': 'மீண்டும் லாகின் செய்யவும்',
  'Ploughing': 'உழவு',
  'Posts are visible to signed-in VIMO users. Share text, a photo or a voice note up to 20 seconds. Ranch records remain private. If publishing times out, retrying the same draft will not create a duplicate.':
      'பதிவுகளை VIMO பயனர்கள் அனைவரும் பார்க்கலாம். எழுத்து, ஒரு புகைப்படம் அல்லது 20 வினாடி வரை குரல் பதிவைப் பகிரலாம். தொழுவப் பதிவுகள் தனிப்பட்டவை. பதிவேற்றம் தாமதமானால் மீண்டும் முயன்றாலும் இரட்டிப்பாகாது.',
  'Pregnancy Injection': 'சினை ஊசி',
  'Pregnancy can only be recorded for a female animal':
      'சினையைப் பசுவுக்கு மட்டுமே பதிவு செய்ய முடியும்',
  'Pregnancy injection': 'சினை ஊசி',
  'Pregnancy started': 'சினை தொடங்கியது',
  'Pregnant cow': 'சினை மாடு',
  'Pregnant cows': 'சினை மாடுகள்',
  'Price per Liter': 'லிட்டருக்கு விலை',
  'Price per Load': 'லோடுக்கு விலை',
  'Problem / Treatment': 'பிரச்சனை / சிகிச்சை',
  'Profile': 'ப்ரொஃபைல்',
  'Pulikulam': 'புளிக்குளம்',
  'Purchase': 'வாங்குதல்',
  'Purchase expense': 'வாங்கிய செலவு',
  'Purchases and ranch milk add stock; deliveries deduct it. Financial entries need a connection. The original author can add or edit notes for five minutes after saving.':
      'வாங்குதலும் தொழுவப் பாலும் இருப்பைக் கூட்டும்; விநியோகம் குறைக்கும். பணப் பதிவுகளுக்கு இணையம் தேவை. பதிவு செய்தவர் சேமித்த 5 நிமிடத்துக்குள் குறிப்பைச் சேர்க்கலாம் அல்லது மாற்றலாம்.',
  'Purple Star': 'ஊதா நட்சத்திரம்',
  'Purpose and preferences': 'பயன்பாடும் விருப்பங்களும்',
  'Ranch ID is available': 'Ranch ID கிடைக்கிறது',
  'Ranch Member': 'தொழுவ உறுப்பினர்',
  'Ranch access is taking too long. Check your connection and try again.':
      'தொழுவ அனுமதிக்கு நேரம் ஆகிறது. இணையத்தைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'Ranch access needs admin approval. Local entries are still saved.':
      'தொழுவ அனுமதிக்கு நிர்வாகியின் ஒப்புதல் தேவை. பதிவுகள் போனில் சேமிக்கப்பட்டுள்ளன.',
  'Ranch member': 'தொழுவ உறுப்பினர்',
  'Rank #': 'தரம் #',
  'Reason': 'காரணம்',
  'Recent Stock Movements': 'சமீபத்திய இருப்பு மாற்றங்கள்',
  'Record milk, cow, calf and manure sales. New sales automatically use the current date and time.':
      'பால், மாடு, கன்று, சாணம் விற்பனையைப் பதிவு செய்யலாம். தேதியும் நேரமும் தானாகச் சேரும்.',
  'Records are saved on this device first and sync to your ranch account. Manual upload and download are available in Cloud Sync.':
      'பதிவுகள் முதலில் இந்த போனில் சேமிக்கப்பட்டு பின் உங்கள் தொழுவக் கணக்குக்கு sync ஆகும்.',
  'Records are written to this device the moment you save them.':
      'சேமித்த உடனே பதிவுகள் இந்த போனில் சேமிக்கப்படும்.',
  'Red Sindhi': 'ரெட் சிந்தி',
  'Register a calf from a pregnant female’s profile. First calving moves a heifer to Cows and starts her lactation.':
      'சினை மாட்டின் profile-ல் கன்றைப் பதிவு செய்யலாம். முதல் ஈற்றில் கிடேரி மாடுகள் பட்டியலுக்கு மாறி கறவை தொடங்கும்.',
  'Rekla race': 'ரேக்ளா பந்தயம்',
  'Repeat': 'மீண்டும்',
  'Request to Join': 'சேரக் கோரிக்கை அனுப்பு',
  'Restore failed. Please choose a valid backup file':
      'மீட்க முடியவில்லை. சரியான backup கோப்பைத் தேர்வு செய்யவும்',
  'Role': 'பொறுப்பு',
  'Running': 'ஓட்டம்',
  'Sahiwal': 'சாஹிவால்',
  'Sahiwal Semen': 'சாஹிவால் விந்து',
  'Sale': 'விற்பனை',
  'Sale Amount': 'விற்பனைத் தொகை',
  'Sale Price / Income': 'விற்பனை விலை / வருமானம்',
  'Sales downloaded': 'விற்பனை download ஆனது',
  'Sat': 'ச',
  'Saturday': 'சனி',
  'Save Doctor Visit': 'மருத்துவப் பதிவைச் சேமி',
  'Save Image': 'படத்தைச் சேமி',
  'Save Milk Entry': 'பால் பதிவைச் சேமி',
  'Save Other Expense': 'இதர செலவைச் சேமி',
  'Save VIMO backup': 'VIMO backup-ஐச் சேமி',
  'Save VIMO report': 'VIMO அறிக்கையைச் சேமி',
  'Save complete VIMO Excel workbook': 'முழு VIMO Excel கோப்பைச் சேமி',
  'Search': 'தேடு',
  'Select Calf': 'கன்றைத் தேர்வு செய்',
  'Select Cow': 'மாட்டைத் தேர்வு செய்',
  'Select customer': 'வாடிக்கையாளரைத் தேர்வு செய்',
  'Sell 1 calf together': '1 கன்றையும் சேர்த்து விற்கவும்',
  'Selling now': 'இப்போது விற்பது',
  'Sep': 'செப்',
  'September': 'செப்டம்பர்',
  'Set the farm name, owner, place, currency and default milk price. Ranch ID stays permanent.':
      'தொழுவப் பெயர், உரிமையாளர், ஊர், நாணயம், பால் விலையை அமைக்கலாம். Ranch ID மாறாது.',
  'Settings saved': 'செட்டிங்ஸ் சேமிக்கப்பட்டன',
  'Share messages with your ranch. Swipe inward from the right edge to open Chat. Swipe inward from the left edge to open Settings.':
      'உங்கள் தொழுவத்துடன் செய்திகளைப் பகிரலாம். வலது ஓரத்திலிருந்து இழுத்தால் சாட், இடது ஓரத்திலிருந்து இழுத்தால் செட்டிங்ஸ்.',
  'Shared with your family': 'குடும்பத்துடன் பகிரப்படும்',
  'Sign in and open your ranch to sync':
      'Sync செய்ய லாகின் செய்து தொழுவத்தைத் திறக்கவும்',
  'Sign in failed': 'லாகின் ஆகவில்லை',
  'Sign in failed. Please try again':
      'லாகின் ஆகவில்லை. மீண்டும் முயற்சிக்கவும்',
  'Signed in': 'லாகின் செய்யப்பட்டது',
  'Some entries have not reached the cloud. They will retry when connected.':
      'சில பதிவுகள் இன்னும் cloud-க்குப் போகவில்லை. இணையம் வந்ததும் மீண்டும் முயற்சிக்கும்.',
  'Start with a letter; use letters, numbers and underscore only':
      'எழுத்தில் தொடங்கவும்; எழுத்து, எண், அடிக்கோடு மட்டும்',
  'Stock Purchase': 'இருப்பு வாங்குதல்',
  'Stock Use': 'இருப்புப் பயன்பாடு',
  'Stock purchases increase the balance. Daily use reduces it. Straw is recorded in bundles; bran in kilograms.':
      'வாங்கினால் இருப்பு கூடும், பயன்படுத்தினால் குறையும். வைக்கோல் கட்டு கணக்கில், தவிடு கிலோ கணக்கில்.',
  'Sun': 'ஞா',
  'Sunday': 'ஞாயிறு',
  'Swimming': 'நீச்சல்',
  'Sync and shared records': 'Sync மற்றும் பகிர்ந்த பதிவுகள்',
  'Sync complete': 'Sync முடிந்தது',
  'Sync needs attention': 'Sync-ஐக் கவனிக்கவும்',
  'Synced': 'Sync ஆனது',
  'Synced ranch milk joins Vendor stock automatically. Existing ranch milk sales and own use are deducted. Corrections and deletions update the same stock once. A negative correction blocks further sales until the stock is corrected.':
      'தொழுவப் பால் வியாபார இருப்பில் தானாகச் சேரும். ஏற்கெனவே விற்ற பாலும் சொந்தப் பயன்பாடும் கழிக்கப்படும். திருத்தங்களும் நீக்கங்களும் இருப்பை ஒருமுறை மட்டும் மாற்றும்.',
  'Syncing...': 'Sync ஆகிறது…',
  'System': 'சிஸ்டம்',
  'Tamed': 'பிடிபட்டது',
  'Tamil entry view - records only': 'பதிவு மட்டும்',
  'Tamil entry view: cows, calves, milk, stock, milk sales, doctor and pregnancy only':
      'பதிவு மட்டும்: மாடு, கன்று, பால், இருப்பு, பால் விற்பனை, மருத்துவம், சினை',
  'Thank you, I will check it': 'நன்றி, பார்க்கிறேன்',
  'That Ranch ID is reserved': 'அந்த Ranch ID ஒதுக்கப்பட்டுள்ளது',
  'That email address does not look right': 'இமெயில் முகவரி சரியாக இல்லை',
  'That email already has an account. Please sign in':
      'இந்த இமெயிலில் ஏற்கெனவே கணக்கு உள்ளது. லாகின் செய்யவும்',
  'That email already has an account. Try signing in':
      'இந்த இமெயிலில் ஏற்கெனவே கணக்கு உள்ளது. லாகின் செய்யவும்',
  'Thavudu': 'தவிடு',
  'The animal must be synced by an admin first':
      'முதலில் நிர்வாகி இந்த மாட்டை sync செய்ய வேண்டும்',
  'The bell opens notification history. Tap an item to mark it read. Daily reminders currently require the app to be active at the reminder time.':
      'மணி ஐகான் அறிவிப்புகளைக் காட்டும். படித்ததாகக் குறிக்கத் தொடவும். தினசரி நினைவூட்டலுக்கு அந்த நேரத்தில் ஆப் திறந்திருக்க வேண்டும்.',
  'The cloud rejected access to some entries. Check ranch membership and the deployed cloud rules. Local entries are kept.':
      'சில பதிவுகளுக்கு cloud அனுமதி தரவில்லை. தொழுவ உறுப்பினர் நிலையைச் சரிபார்க்கவும். போனில் உள்ள பதிவுகள் பாதுகாப்பாக உள்ளன.',
  'The dashboard shows today’s milk, animals, expenses, sales and the latest ranch activity.':
      'முகப்பில் இன்றைய பால், மாடுகள், செலவு, விற்பனை, சமீபத்திய செயல்பாடுகள் தெரியும்.',
  'The five-minute edit time has expired':
      '5 நிமிடத் திருத்த நேரம் முடிந்துவிட்டது',
  'The ranch admin will receive your request. Ranch data stays private until they approve it.':
      'உங்கள் கோரிக்கை தொழுவ நிர்வாகிக்குப் போகும். அவர் ஏற்கும் வரை தொழுவ விவரங்கள் தெரியாது.',
  'The ranch does not wait for a signal, and neither does this app.':
      'தொழுவம் சிக்னலுக்காகக் காத்திருக்காது; இந்த ஆப்பும் அப்படித்தான்.',
  'There are no active calves on the ranch.': 'தொழுவத்தில் கன்றுகள் இல்லை.',
  'There are no active cows on the ranch.': 'தொழுவத்தில் மாடுகள் இல்லை.',
  'This Month': 'இந்த மாதம்',
  'This Ranch ID is already taken': 'இந்த Ranch ID ஏற்கெனவே எடுக்கப்பட்டுள்ளது',
  'This Week': 'இந்த வாரம்',
  'This Year': 'இந்த ஆண்டு',
  'This member': 'இந்த உறுப்பினர்',
  'This photo exceeds 8 MB': 'இந்தப் புகைப்படம் 8 MB-க்கு மேல் உள்ளது',
  'This record is no longer available.': 'இந்தப் பதிவு இப்போது இல்லை.',
  'This record may have been removed or synced away.':
      'இந்தப் பதிவு நீக்கப்பட்டிருக்கலாம்.',
  'Thu': 'வி',
  'Thursday': 'வியாழன்',
  'Today': 'இன்று',
  'Today\'s Milk Balance': 'இன்றைய பால் இருப்பு',
  'Too many attempts. Please wait a moment':
      'பல முறை முயற்சித்துவிட்டீர்கள். சிறிது நேரம் காத்திருக்கவும்',
  'Total Purchase Amount': 'மொத்த வாங்கிய தொகை',
  'Totals appear here once you record milk or money.':
      'பால் அல்லது பணம் பதிவு செய்ததும் மொத்தம் இங்கே தெரியும்.',
  'Tue': 'செ',
  'Tuesday': 'செவ்வாய்',
  'Umbalachery': 'உம்பளச்சேரி',
  'Unable to open': 'திறக்க முடியவில்லை',
  'Unknown': 'தெரியாது',
  'Unknown Mother': 'தாய் தெரியாது',
  'Unknown breed': 'இனம் தெரியாது',
  'Upload milk data': 'பால் விவரத்தை upload செய்',
  'Usage': 'பயன்பாடு',
  'Use + to add milk, stock use or an expense. On Recent Activity, use the three-dot menu to edit your entry for five minutes or add a note.':
      '+ அழுத்தி பால், இருப்புப் பயன்பாடு அல்லது செலவைச் சேர்க்கலாம். சமீபத்திய செயல்பாடுகளில் மூன்று புள்ளி menu மூலம் 5 நிமிடத்துக்குள் திருத்தலாம்.',
  'Use Stock': 'இருப்பைப் பயன்படுத்து',
  'Use at least 4 characters': 'குறைந்தது 4 எழுத்துகள் வேண்டும்',
  'Use no more than 24 characters': '24 எழுத்துகளுக்கு மேல் வேண்டாம்',
  'Usernames are unique, ignore letter case, and can be changed once every 30 days. Use 3–20 letters, numbers or underscores, starting with a letter. Availability is checked online; saving reserves the name atomically.':
      'VIMO ID ஒவ்வொருவருக்கும் தனித்துவமானது; பெரிய/சிறிய எழுத்து வேறுபாடு இல்லை; 30 நாளுக்கு ஒருமுறை மாற்றலாம். 3–20 ஆங்கில எழுத்து, எண் அல்லது அடிக்கோடு பயன்படுத்தவும்; எழுத்தில் தொடங்கவும். கிடைக்கிறதா என்பது ஆன்லைனில் பார்க்கப்படும்.',
  'VIMO Ranch update': 'VIMO தொழுவச் செய்தி',
  'Vadivasal practice': 'வாடிவாசல் பயிற்சி',
  'Vaikol': 'வைக்கோல்',
  'Vendor milk is separate from ranch milk. Purchases add litres, deliveries deduct litres, and payments reduce the person’s outstanding balance. Vendor financial entries require internet so two devices cannot sell the same stock. Notes may be changed by the author within five minutes. Payment frequency records the agreed arrangement; it does not automatically charge anyone.':
      'வியாபாரப் பால் தொழுவப் பாலிலிருந்து தனி. வாங்கினால் லிட்டர் கூடும், கொடுத்தால் குறையும், பணம் வந்தால் பாக்கி குறையும். பதிவு செய்தவர் 5 நிமிடத்துக்குள் குறிப்பை மாற்றலாம். பணம் செலுத்தும் முறை ஒப்பந்தத்தைப் பதிவு செய்யும்; யாரிடமும் தானாகப் பணம் எடுக்காது.',
  'Vendor stock and payments': 'வியாபார இருப்பும் பணமும்',
  'Waiting': 'காத்திருக்கிறது',
  'Waiting for sync': 'Sync-க்காகக் காத்திருக்கிறது',
  'Waiting to sync': 'Sync-க்காகக் காத்திருக்கிறது',
  'Walking': 'நடைப் பயிற்சி',
  'Wed': 'பு',
  'Wednesday': 'புதன்',
  'Week': 'வாரம்',
  'Weekly · Sun': 'வாரம் · ஞாயிறு',
  'Welcome back': 'மீண்டும் வருக',
  'When the network returns, pending records upload on their own.':
      'இணையம் வந்ததும் நிலுவைப் பதிவுகள் தானாக upload ஆகும்.',
  'Will retry automatically': 'தானாக மீண்டும் முயற்சிக்கும்',
  'Won': 'வெற்றி',
  'Working offline': 'இணையம் இல்லாமல் இயங்குகிறது',
  'Year': 'ஆண்டு',
  'You cannot change your own admin role':
      'உங்கள் நிர்வாகப் பொறுப்பை நீங்களே மாற்ற முடியாது',
  'You cannot remove yourself': 'உங்களை நீங்களே நீக்க முடியாது',
  'Your Name': 'உங்கள் பெயர்',
  'Your ranch role does not allow adding doctor visits':
      'உங்கள் பொறுப்புக்கு மருத்துவப் பதிவு அனுமதி இல்லை',
  'Your ranch role does not allow adding entries':
      'உங்கள் பொறுப்புக்குப் பதிவு செய்ய அனுமதி இல்லை',
  'Your ranch role does not allow adding milk records':
      'உங்கள் பொறுப்புக்குப் பால் பதிவு செய்ய அனுமதி இல்லை',
  'Your ranch role does not allow adding stock':
      'உங்கள் பொறுப்புக்கு இருப்பு சேர்க்க அனுமதி இல்லை',
  'Your ranch role does not allow doctor entries':
      'உங்கள் பொறுப்புக்கு மருத்துவப் பதிவு அனுமதி இல்லை',
  'Your ranch role does not allow pregnancy updates':
      'உங்கள் பொறுப்புக்குச் சினைப் பதிவு அனுமதி இல்லை',
  'Your ranch role does not allow recording sales':
      'உங்கள் பொறுப்புக்கு விற்பனைப் பதிவு அனுமதி இல்லை',
  'Ranch - Excel Workbook': 'தொழுவம் — Excel',
  'VIMO \u2022 Manage. Care. Grow.':
      'VIMO \u2022 நிர்வகி. பராமரி. வளர்ச்சி பெறு.',
  'Owner': 'உரிமையாளர்',
  'Added By': 'பதிவு செய்தவர்',
  'Price Per Unit': 'ஒரு அலகு விலை',
  'Category': 'வகை',
  'Type': 'வகை',
  'Own Use': 'சொந்தப் பயன்பாடு',
  'Item': 'பொருள்',
  'Movement': 'இருப்பு மாற்றம்',
  'Quantity Kg': 'அளவு (கிலோ)',
  'Injection': 'ஊசி',
  'Session': 'நேரம்',
  'Food Label': 'தீவனம்',
  'Unit': 'அலகு',
  'Person': 'நபர்',
  'Kind': 'வகை',
  'Paid': 'செலுத்தியது',
  'Sender': 'அனுப்பியவர்',
  'Title': 'தலைப்பு',
  'Assignee': 'வேலை ஒதுக்கப்பட்டவர்',
  'Completed By': 'முடித்தவர்',
  'Supplier': 'விற்பவர்',
  'Customer': 'வாடிக்கையாளர்',
  'Price Per Liter': 'லிட்டருக்கு விலை',
  'Cow Name': 'மாட்டின் பெயர்',
  'Details': 'விவரம்',
  'Received': 'வாங்கியது',
  'Mother': 'தாய்',
  'Status': 'நிலை',
  'Updated By': 'மாற்றியவர்',
  'Due': 'பாக்கி',
  'Place': 'ஊர்',
  'Contact': 'தொடர்பு',
};
